### ISSUE TITLE
exception: No such file or directory: 'sra-stat'

### ISSUE THREAD

**Issue by dtenenba** [rvalieris/parallel-fastq-dump#10]
I am trying to run parallel-fastq-dump on an SRA file that is already downloaded, and get an error:

```
root@4eb8d72f7f10:~/ncbi/dbGaP-0/sra# /root/miniconda3/bin/parallel-fastq-dump --sra-id SRR1219902.sra --threads 10 --outdir out2
SRR ids: ['SRR1219902.sra']
extra args: []
Traceback (most recent call last):
  File "/root/miniconda3/bin/parallel-fastq-dump", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-fastq-dump==0.6.2', 'parallel-fastq-dump')
  File "/root/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/root/miniconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 100, in <module>
  File "/root/miniconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 92, in main
  File "/root/miniconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 47, in get_spot_count
  File "/root/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sra-stat': 'sra-stat'
```

**Comment by rvalieris** [comment]
> No such file or directory: 'sra-stat'

hello,
the tools `sra-stat` and `fastq-dump` from `sra-tools` are necessary for parallel-fastq-dump to work, make sure they are in your `$PATH`.
