### ISSUE TITLE
OSError: [Errno 39] Directory not empty: '2' 

### ISSUE THREAD

**Issue by arglatha** [rvalieris/parallel-fastq-dump#22]
Hello! 

This is my first time running parallel-fastq-dump so I apologize if this is a easy fix. Below I will post the output I receive from the program. 

(base) [arglatha]$ parallel-fastq-dump --sra-id SRR6820613  --threads 6 --outdir ./SRR6820613/ --split-files --gzip --tmpdir ./tmp/
SRR ids: ['SRR6820613']
extra args: ['--split-files', '--gzip']
tempdir: ./tmp/pfd_kh5jeeyw
SRR6820613 spots: 75623640
blocks: [[1, 12603940], [12603941, 25207880], [25207881, 37811820], [37811821, 50415760], [50415761, 63019700], [63019701, 75623640]]
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:04:38 fastq-dump.2.9.6 int: storage exhausted while writing file within file system module - switching cache-tee-file to read-only
2019-08-12T15:13:04 fastq-dump.2.9.6 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2019-08-12T15:15:52 fastq-dump.2.9.6 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2019-08-12T15:18:40 fastq-dump.2.9.6 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2019-08-12T15:58:34 fastq-dump.2.9.6 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
fastq-dump error! exit code: -24
Exception ignored in: <finalize object at 0x7f29c0854460; dead>
Traceback (most recent call last):
  File "/util/common/bioinformatics/bioconda/miniconda3-4.6.14/lib/python3.7/weakref.py", line 552, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/util/common/bioinformatics/bioconda/miniconda3-4.6.14/lib/python3.7/tempfile.py", line 795, in _cleanup
    _shutil.rmtree(name)
  File "/util/common/bioinformatics/bioconda/miniconda3-4.6.14/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/util/common/bioinformatics/bioconda/miniconda3-4.6.14/lib/python3.7/shutil.py", line 433, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/util/common/bioinformatics/bioconda/miniconda3-4.6.14/lib/python3.7/shutil.py", line 431, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
**OSError: [Errno 39] Directory not empty: '2'**

Any advice would be appreciated!

**Comment by rvalieris** [comment]
hello,

`2019-08-12T15:04:38 fastq-dump.2.9.6 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'`
this means you are running out of space.

`fastq-dump error! exit code: -24`
and fastq-dump could not finish running correctly.

verify how much space you have left. you might need to run this on another partition with more space.
