### ISSUE TITLE
TemporaryDirectory error

### ISSUE THREAD

**Issue by dgiovannelli** [rvalieris/parallel-fastq-dump#27]
Hi @rvalieris ,
first thank you for developing this tool. I was doing a search for better SRA download and found a three of tweets pointing to this. Great stuff.

I am having trouble making the script work on our server. It runs fine in my local computer, but on the server I get this error:

```
SRR ids: ['DRR093002']
extra args: ['--split-files', '--gzip']
Traceback (most recent call last):
  File "parallel-fastq-dump.py", line 119, in <module>
    main()
  File "parallel-fastq-dump.py", line 112, in main
    pfd(args, si, extra_args)
  File "parallel-fastq-dump.py", line 12, in pfd
    tmp_dir = tempfile.TemporaryDirectory(prefix="pfd_",dir=args.tmpdir)
AttributeError: 'module' object has no attribute 'TemporaryDirectory'
```

here the call
```
parallel-fastq-dump --sra-id DRR093002 --threads 16 --outdir out/ --split-files --gzip
```

I've been googling for a solution, but I cannot find and obvious one. When I run parallel-fastq-dump by itself I get the list of options just fine.

Any suggestions?
D

**Comment by dgiovannelli** [comment]
FOund the solution. I was running python 2.7 as default. Solved the error by calling 
```
python3 parallel-fastq-dump.py
```
Thank you anyway!
D
