### ISSUE TITLE
Error message appear after running

### ISSUE THREAD

**Issue by kubotakehiro** [rvalieris/parallel-fastq-dump#50]
Hello, I'm getting this error while I was analyzing.
I'm using ubuntu on WSL.

$ parallel-fastq-dump --threads 8 --split-files --gzip --sra-id SRR2244401
2022-10-05 10:14:30,278 - SRR ids: ['SRR2244401']
2022-10-05 10:14:30,278 - extra args: ['--split-files', '--gzip']
2022-10-05 10:14:30,283 - tempdir: /tmp/pfd_hec73ych
2022-10-05 10:14:30,283 - CMD: sra-stat --meta --quick SRR2244401
Traceback (most recent call last):
  File "/home/takehiro/miniconda3/bin/parallel-fastq-dump", line 116, in get_spot_count
    total += int(l.split('|')[2].split(':')[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/takehiro/miniconda3/bin/parallel-fastq-dump", line 181, in <module>
    main()
  File "/home/takehiro/miniconda3/bin/parallel-fastq-dump", line 175, in main
    pfd(args, si, extra_args)
  File "/home/takehiro/miniconda3/bin/parallel-fastq-dump", line 49, in pfd
    n_spots = get_spot_count(srr_id)
  File "/home/takehiro/miniconda3/bin/parallel-fastq-dump", line 122, in get_spot_count
    raise IndexError(msg.format('\n'.join(txt), '\n'.join(etxt)))
IndexError: sra-stat output parsing error!
--sra-stat STDOUT--

--sra-stat STDERR--
2022-10-05T01:14:30 sra-stat.2.8.0 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )
2022-10-05T01:14:30 sra-stat.2.8.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
2022-10-05T01:14:31 sra-stat.2.8.0 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )
2022-10-05T01:14:31 sra-stat.2.8.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
2022-10-05T01:14:31 sra-stat.2.8.0 int: directory not found while opening manager within virtual file system module - 'SRR2244401'

**Comment by rvalieris** [comment]
hello, the error is due to your version of sra-tools, see [this message](https://github.com/ncbi/sra-tools):
```
August 4, 2022 : Security Update

Due to updated security at NCBI, versions of the SRA Toolkit 2.9.6 and older will no longer 
be able to connect to the NCBI data location service. 
We advise impacted users to update to the latest version of the SRA Toolkit.
```

**Comment by kubotakehiro** [comment]
Thank you, I updated sra-tools. Then the command successfully worked.
