### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Kiliankleemann** [rvalieris/parallel-fastq-dump#54]
I installed an ARM64 conda environment and loaded:
conda install parallel-fastq-dump 'sra-tools>=3.0.0'

I used this execution: 
cat SRR_Acc_List.txt | while read sample; do 
	parallel-fastq-dump --sra-id ${sample} --threads 4 --outdir fastq_files/ --split-files --gzip
done

Traceback (most recent call last):
  File "/Users/kiliankleemann/anaconda3/envs/SRA_toolkit/bin/parallel-fastq-dump", line 116, in get_spot_count
    total += int(l.split('|')[2].split(':')[0])
                 ~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kiliankleemann/anaconda3/envs/SRA_toolkit/bin/parallel-fastq-dump", line 181, in <module>
    main()
  File "/Users/kiliankleemann/anaconda3/envs/SRA_toolkit/bin/parallel-fastq-dump", line 175, in main
    pfd(args, si, extra_args)
  File "/Users/kiliankleemann/anaconda3/envs/SRA_toolkit/bin/parallel-fastq-dump", line 49, in pfd
    n_spots = get_spot_count(srr_id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/envs/SRA_toolkit/bin/parallel-fastq-dump", line 122, in get_spot_count
    raise IndexError(msg.format('\n'.join(txt), '\n'.join(etxt)))
IndexError: sra-stat output parsing error!

**Comment by rvalieris** [comment]
Hello, can you tell me which SRR are you trying to download that produced this error ?

also run this command and show me the output:
`sra-stat --meta --quick <SRR>`

**Comment by Lsz-20** [comment]
The same question.
`2023-09-28T01:08:30 sra-stat.3.0.8 sys: encryption failed while validating token within cryptographic module - Verification issue 0xC for this certificate: (  cert. version     : 3  serial number     : 0A:75:A4:D0:FD:F0:ED:BF:93:72:16:E5:84:AD:26:CE:F6:6C:B5:75  issuer name       : CN=demotest.doctorcom.com, O=Doctorcom LTD., C=CN  subject name      : CN=demotest.doctorcom.com, O=Doctorcom LTD., C=CN  issued  on        : 2019-09-09 09:20:26  expires on        : 2039-10-24 09:20:26  signed using      : RSA with SHA-256  RSA key size      : 2048 bits  basic constraints : CA=true  )
2023-09-28T01:08:30 sra-stat.3.0.8 sys: mbedtls_ssl_get_verify_result for 'locate.ncbi.nlm.nih.gov' returned 0xC ( !! The certificate Common Name (CN) does not match with the expected CN  !! The certificate is not correctly signed by the trusted CA )
2023-09-28T01:08:30 sra-stat.3.0.8 sys: encryption failed while validating token within cryptographic module - Verification issue 0xC for this certificate: (  cert. version     : 3  serial number     : 0A:75:A4:D0:FD:F0:ED:BF:93:72:16:E5:84:AD:26:CE:F6:6C:B5:75  issuer name       : CN=demotest.doctorcom.com, O=Doctorcom LTD., C=CN  subject name      : CN=demotest.doctorcom.com, O=Doctorcom LTD., C=CN  issued  on        : 2019-09-09 09:20:26  expires on        : 2039-10-24 09:20:26  signed using      : RSA with SHA-256  RSA key size      : 2048 bits  basic constraints : CA=true  )
2023-09-28T01:08:30 sra-stat.3.0.8 sys: mbedtls_ssl_get_verify_result for 'locate.ncbi.nlm.nih.gov' returned 0xC ( !! The certificate Common Name (CN) does not match with the expected CN  !! The certificate is not correctly signed by the trusted CA )
2023-09-28T01:08:30 sra-stat.3.0.8 int: directory not found while opening manager within virtual file system module - 'SRR9883230'`
Perhaps the SRR doc not exist？

**Comment by rvalieris** [comment]
@Lsz-20 , thats a different error.

the SRR exists and I can't reproduce your issue, this error message suggests a network / firewall issue I think.

**Comment by Kiliankleemann** [comment]
managed to fix it with the loop calling.

**Comment by Lsz-20** [comment]
> managed to fix it with the loop calling.
Maybe we can say more about how to operate it?
