### ISSUE TITLE
IndexError: sra-stat output parsing error!

### ISSUE THREAD

**Issue by Naturalist1986** [rvalieris/parallel-fastq-dump#55]
Hi, I'm installed parallel-fastq-dump on a cluster using SLURM, but i get this error: 

(srr_download) moshea@moriah-gw-01:~$ parallel-fastq-dump --sra-id SRR2244401 --threads 4 --outdir . --split-files --gzip -T .
2024-01-07 12:31:15,300 - SRR ids: ['SRR2244401']
2024-01-07 12:31:15,300 - extra args: ['--split-files', '--gzip']
2024-01-07 12:31:15,304 - tempdir: /sci/home/moshea/pfd_xr6lq4eh
2024-01-07 12:31:15,304 - CMD: sra-stat --meta --quick SRR2244401
Traceback (most recent call last):
  File "/sci/home/moshea/miniconda3/envs/srr_download/bin/parallel-fastq-dump", line 116, in get_spot_count
    total += int(l.split('|')[2].split(':')[0])
                 ~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sci/home/moshea/miniconda3/envs/srr_download/bin/parallel-fastq-dump", line 181, in <module>
    main()
  File "/sci/home/moshea/miniconda3/envs/srr_download/bin/parallel-fastq-dump", line 175, in main
    pfd(args, si, extra_args)
  File "/sci/home/moshea/miniconda3/envs/srr_download/bin/parallel-fastq-dump", line 49, in pfd
    n_spots = get_spot_count(srr_id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/sci/home/moshea/miniconda3/envs/srr_download/bin/parallel-fastq-dump", line 122, in get_spot_count
    raise IndexError(msg.format('\n'.join(txt), '\n'.join(etxt)))
IndexError: sra-stat output parsing error!
--sra-stat STDOUT--

--sra-stat STDERR--

It works on  a private server, but not on the cluster. Can you help?

**Comment by rvalieris** [comment]
Hello,

this could be a version or network issue, first check that you have the latest version of sra-tools and try this command:
`sra-stat --meta --quick SRR2244401`

you should get this output:
`SRR2244401|D23G3.1|110485:22317970:22317970|:|:|:`

**Comment by Naturalist1986** [comment]
This gives a similar error:

(srr_download) moshea@moriah-gw-01:/sci/backup/aerez/aerez/moshea/ncbi_mags$ srun sra-stat --meta --quick SRR2244401
srun: job 20797919 queued and waiting for resources
srun: job 20797919 has been allocated resources
2024-01-10T13:10:32 sra-stat.3.0.10 int: directory not found while opening manager within virtual file system module - 'SRR2244401'
srun: error: glacier-03: task 0: Exited with exit code 3

**Comment by rvalieris** [comment]
did you follow these steps to configure the toolkit ? https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration

if it works without slurm, it might be because the config files are not visible in the node.
