### ISSUE TITLE
Problem running parallel-fastq-dump on a cluster

### ISSUE THREAD

**Issue by samuelCollombet** [rvalieris/parallel-fastq-dump#7]
Hi,
Sorry for bothering you with a very basic problem...
I have tried to install parallel-fastq-dump locally on our cluster after cloning it from git :
```
$ python setup.py --prefix=/data/users/scollomb/programs
$echo $PYTHONPATH
/bioinfo/local/build/Centos/python/python-2.7.12/lib/python2.7/site-packages/:/data/users/scollomb/programs/lib/python2.7/site-packages

```
 but I cannot run it : 

```
parallel-fastq-dump --tmpdir /data/tmp/scollomb --threads 10 -O ./ -s SRR3933583 --split-3 --gzip
SRR ids: ['SRR3933583']
extra args: ['--split-3', '--gzip']
Traceback (most recent call last):
  File "/data/users/scollomb/programs/bin/parallel-fastq-dump", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-fastq-dump==0.6.2', 'parallel-fastq-dump')
  File "/bioinfo/local/build/Centos/python/python-2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/bioinfo/local/build/Centos/python/python-2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/data/users/scollomb/programs/lib/python2.7/site-packages/parallel_fastq_dump-0.6.2-py2.7.egg/EGG-INFO/scripts/parallel-fastq-dump", line 100, in <module>
    
  File "/data/users/scollomb/programs/lib/python2.7/site-packages/parallel_fastq_dump-0.6.2-py2.7.egg/EGG-INFO/scripts/parallel-fastq-dump", line 92, in main
    
  File "/data/users/scollomb/programs/lib/python2.7/site-packages/parallel_fastq_dump-0.6.2-py2.7.egg/EGG-INFO/scripts/parallel-fastq-dump", line 47, in get_spot_count
    
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```
Any idea what is going on?

**Comment by rvalieris** [comment]
hi,

looks like its failing on the subprocess call, make sure you have the `sra-stat` and `fastq-dump` binaries on your `PATH`.
